import type { LucideIcon } from "lucide-react";
import {
  Cpu, Trophy, CalendarClock, Gauge, GitBranch, MessagesSquare, BarChart3,
  ShieldCheck, Network, FileText, CheckSquare, Users, Bell, LayoutDashboard,
  Globe2, Server, GraduationCap, Zap, Lock, Radio, Layers,
  Workflow, Clock, Bot, Database, Bell as BellIcon,
} from "lucide-react";

export type MarketingPage = {
  eyebrow: string;
  title: React.ReactNode;
  description: string;
  stats?: { value: string; label: string }[];
  features: { icon: LucideIcon; title: string; desc: string }[];
  bullets?: string[];
};

export const platformPages: Record<string, MarketingPage> = {
  automation: {
    eyebrow: "Automation Engine",
    title: <>The engine that <span className="text-gradient-cyan">runs itself.</span></>,
    description: "An event-driven orchestration core that reacts to every registration, check-in, score, and dispute the instant it happens — no human in the loop.",
    stats: [{ value: "~38ms", label: "Event latency" }, { value: "6-core", label: "Orchestrator" }, { value: "99.99%", label: "Uptime" }, { value: "0", label: "Manual steps" }],
    features: [
      { icon: Workflow, title: "Event pipeline", desc: "Every action fires a typed event that ripples through dependent systems instantly." },
      { icon: Zap, title: "Zero-copy dispatch", desc: "Sub-50ms reaction time from trigger to resolution across the whole platform." },
      { icon: Bot, title: "Policy engine", desc: "Define rules once — no-shows, subs, and disputes resolve automatically by policy." },
      { icon: Clock, title: "Scheduled jobs", desc: "Windowed check-ins, reminders, and escalations run precisely on time, every time." },
      { icon: Radio, title: "Realtime sync", desc: "Brackets, dashboards, and Discord stay perfectly in lockstep as results land." },
      { icon: Database, title: "Immutable log", desc: "Every automated decision is recorded to an auditable, append-only event log." },
    ],
    bullets: ["Reacts in real time to every platform event", "Configurable per-tournament policy rules", "Fully auditable automation history"],
  },
  "tournament-engine": {
    eyebrow: "Tournament Engine",
    title: <>Every format. <span className="text-gradient-cyan">One engine.</span></>,
    description: "Single & double elimination, Swiss, round-robin, gauntlet, and multi-stage combinations — generated, seeded, and recomputed automatically.",
    stats: [{ value: "8+", label: "Formats" }, { value: "4096", label: "Max players" }, { value: "Live", label: "Recompute" }, { value: "0", label: "Broken brackets" }],
    features: [
      { icon: GitBranch, title: "Any format", desc: "Elimination, Swiss, round-robin, gauntlet, and custom multi-stage flows." },
      { icon: Gauge, title: "Smart seeding", desc: "Conflict-aware seeding across timezones, streams, and prior placements." },
      { icon: Trophy, title: "Auto-advance", desc: "Winners advance the moment scores are confirmed — no manual bracket edits." },
      { icon: Layers, title: "Multi-stage", desc: "Chain group stages into playoffs with automatic qualification logic." },
      { icon: CheckSquare, title: "Tiebreakers", desc: "Configurable tiebreak rules resolve standings deterministically." },
      { icon: Cpu, title: "No-show handling", desc: "Brackets self-heal when a player fails to check in — instantly." },
    ],
  },
  scheduler: {
    eyebrow: "Scheduler",
    title: <>Timing that <span className="text-gradient-cyan">never conflicts.</span></>,
    description: "Conflict-aware scheduling across timezones, streams, and venues. Reschedules ripple through every dependent match automatically.",
    stats: [{ value: "12", label: "Timezones" }, { value: "Auto", label: "Conflict scan" }, { value: "Live", label: "Reschedule" }, { value: "24/7", label: "Reminders" }],
    features: [
      { icon: CalendarClock, title: "Conflict detection", desc: "Automatically prevents overlapping matches for players, casters, and courts." },
      { icon: Globe2, title: "Timezone-aware", desc: "Every participant sees times in their own timezone, always correct." },
      { icon: Bell, title: "Smart reminders", desc: "Players and staff are pinged exactly when they need to be — not before." },
      { icon: Radio, title: "Live reschedule", desc: "Move one match and every dependency updates in real time." },
      { icon: Server, title: "Stream slots", desc: "Assign matches to broadcast slots with automatic overlap protection." },
      { icon: Clock, title: "Buffer logic", desc: "Configurable buffers absorb overruns without cascading delays." },
    ],
  },
  matchmaking: {
    eyebrow: "Matchmaking",
    title: <>Fair pairings, <span className="text-gradient-cyan">computed instantly.</span></>,
    description: "Rating-aware seeding and pairing that keeps every round competitive — from opening matches to the grand final.",
    stats: [{ value: "Elo", label: "Rating model" }, { value: "<1s", label: "Pair time" }, { value: "Live", label: "Re-seed" }, { value: "Fair", label: "By design" }],
    features: [
      { icon: Gauge, title: "Rating-aware", desc: "Seeds by skill rating so early rounds stay meaningful and balanced." },
      { icon: Users, title: "Region balancing", desc: "Minimizes cross-region latency where format allows." },
      { icon: GitBranch, title: "Swiss pairing", desc: "Buchholz-based Swiss pairings computed in under a second per round." },
      { icon: ShieldCheck, title: "Collusion guard", desc: "Detects and prevents suspicious repeat pairings automatically." },
      { icon: Cpu, title: "Instant recompute", desc: "Drops and subs trigger immediate, fair re-pairing." },
      { icon: BarChart3, title: "Strength of schedule", desc: "Tracks SoS to inform tiebreakers and standings." },
    ],
  },
  "live-brackets": {
    eyebrow: "Live Brackets",
    title: <>Brackets that <span className="text-gradient-cyan">update themselves.</span></>,
    description: "Real-time bracket trees that recompute the instant a score is reported. Spectators, players, and casters see the same truth simultaneously.",
    stats: [{ value: "Realtime", label: "Updates" }, { value: "∞", label: "Spectators" }, { value: "Live", label: "Standings" }, { value: "1s", label: "Propagation" }],
    features: [
      { icon: GitBranch, title: "Live trees", desc: "Bracket visualizations update the moment results are confirmed." },
      { icon: Radio, title: "Realtime push", desc: "Every viewer sees updates within a second, no refresh needed." },
      { icon: Trophy, title: "Auto-advance", desc: "Winners flow forward automatically with animated transitions." },
      { icon: BarChart3, title: "Live standings", desc: "Group tables and leaderboards recompute in real time." },
      { icon: MessagesSquare, title: "Caster mode", desc: "A broadcast-ready overlay view for streamers and casters." },
      { icon: Layers, title: "Embeddable", desc: "Drop live brackets into any site or overlay with one link." },
    ],
  },
  discord: {
    eyebrow: "Discord Integration",
    title: <>Native to Discord. <span className="text-gradient-cyan">Not a bot.</span></>,
    description: "Roles, channels, permissions, and match threads provisioned the instant a tournament is born — orchestrated by the platform, not bolted on.",
    stats: [{ value: "Auto", label: "Provisioning" }, { value: "1-click", label: "Setup" }, { value: "Live", label: "Threads" }, { value: "0", label: "Slash spam" }],
    features: [
      { icon: MessagesSquare, title: "Match threads", desc: "Every match gets a thread with scores, comms, and an audit trail." },
      { icon: Users, title: "Role sync", desc: "Player, captain, and staff roles assigned automatically on entry." },
      { icon: Bell, title: "Smart pings", desc: "Participants notified only when it matters — across timezones." },
      { icon: ShieldCheck, title: "Permission guard", desc: "Channels lock and unlock automatically as matches progress." },
      { icon: Network, title: "Server topology", desc: "Categories and channels structured to match your bracket." },
      { icon: Radio, title: "Live results", desc: "Scores and advancements posted to channels in real time." },
    ],
  },
  analytics: {
    eyebrow: "Analytics",
    title: <>Every match becomes <span className="text-gradient-cyan">structured data.</span></>,
    description: "Player histories, head-to-head records, and org-wide dashboards. Trustworthy numbers your sponsors and staff can rely on.",
    stats: [{ value: "2.4M+", label: "Players tracked" }, { value: "12.4M+", label: "Matches" }, { value: "CSV/API", label: "Exports" }, { value: "Live", label: "Dashboards" }],
    features: [
      { icon: BarChart3, title: "Org dashboards", desc: "Real-time overviews across every event you run." },
      { icon: Users, title: "Player histories", desc: "Complete career records, ratings, and trends per player." },
      { icon: GitBranch, title: "Head-to-head", desc: "Rivalry data and matchup breakdowns computed automatically." },
      { icon: Database, title: "Data exports", desc: "Clean CSV and API exports for sponsors and BI tools." },
      { icon: Radio, title: "Live viewership", desc: "Concurrency, watch-time, and engagement in real time." },
      { icon: FileText, title: "Auto reports", desc: "Post-event recaps generated the moment a final ends." },
    ],
  },
  architecture: {
    eyebrow: "Architecture",
    title: <>Engineered like <span className="text-gradient-cyan">infrastructure.</span></>,
    description: "A globally distributed, event-driven system built for the split-second demands of live competitive operations at planetary scale.",
    stats: [{ value: "28", label: "Edge regions" }, { value: "99.99%", label: "Uptime SLA" }, { value: "~38ms", label: "P50 latency" }, { value: "Zero", label: "Downtime deploys" }],
    features: [
      { icon: Network, title: "Event-driven core", desc: "Everything is an event flowing through a typed, durable pipeline." },
      { icon: Globe2, title: "Global edge", desc: "Requests served from 28 regions for worldwide low latency." },
      { icon: Database, title: "Durable log", desc: "Append-only event store enables perfect replay and audit." },
      { icon: Server, title: "Horizontal scale", desc: "Scales elastically to thousands of concurrent tournaments." },
      { icon: Lock, title: "Isolated tenants", desc: "Every guild is logically isolated with strict boundaries." },
      { icon: Zap, title: "Zero-downtime", desc: "Rolling deploys ship changes without interrupting live events." },
    ],
  },
  security: {
    eyebrow: "Security",
    title: <>Enterprise-grade <span className="text-gradient-cyan">by default.</span></>,
    description: "SOC 2 controls, SSO/SAML, granular roles, and full audit trails — so global organizations can trust Tournament OS with their biggest events.",
    stats: [{ value: "SOC 2", label: "Type II" }, { value: "ISO", label: "27001" }, { value: "SSO", label: "SAML/OIDC" }, { value: "100%", label: "Audited" }],
    features: [
      { icon: ShieldCheck, title: "SOC 2 · ISO 27001", desc: "Independently audited controls across the entire platform." },
      { icon: Lock, title: "SSO / SAML", desc: "Enterprise identity with SAML and OIDC providers." },
      { icon: Users, title: "Granular roles", desc: "Role-based access down to the individual action." },
      { icon: FileText, title: "Audit trails", desc: "Every action recorded to an immutable, exportable log." },
      { icon: Database, title: "Data residency", desc: "Choose where your data lives to meet compliance needs." },
      { icon: Server, title: "Encryption", desc: "AES-256 at rest, TLS 1.3 in transit, everywhere." },
    ],
  },
};

export const featurePages: Record<string, MarketingPage> = {
  registration: {
    eyebrow: "Registration",
    title: <>Sign-ups that <span className="text-gradient-cyan">gate themselves.</span></>,
    description: "Controlled registration with caps, waitlists, custom fields, and requirements — enforced automatically the instant a player enters.",
    features: [
      { icon: FileText, title: "Custom forms", desc: "Collect exactly the data you need with typed, validated fields." },
      { icon: Users, title: "Caps & waitlists", desc: "Automatic waitlists promote players as slots free up." },
      { icon: CheckSquare, title: "Requirements", desc: "Enforce rank, region, and account requirements on entry." },
      { icon: ShieldCheck, title: "Duplicate guard", desc: "Detects and blocks duplicate and alt-account sign-ups." },
      { icon: Bell, title: "Confirmations", desc: "Instant confirmation and reminder flows out of the box." },
      { icon: LayoutDashboard, title: "Live roster", desc: "Watch entries arrive and verify in real time." },
    ],
  },
  verification: {
    eyebrow: "Verification",
    title: <>Verified before they <span className="text-gradient-cyan">touch a bracket.</span></>,
    description: "Account, region, and eligibility checks run automatically the moment a player registers — stopping smurfs before the damage is done.",
    features: [
      { icon: ShieldCheck, title: "Account checks", desc: "Verify linked game accounts and identity automatically." },
      { icon: Globe2, title: "Region locks", desc: "Enforce region eligibility with real geolocation." },
      { icon: Users, title: "Anti-smurf", desc: "Statistical smurf detection flags suspicious entries." },
      { icon: Lock, title: "Eligibility rules", desc: "Rank floors, ceilings, and custom criteria enforced on entry." },
      { icon: Bell, title: "Instant flags", desc: "Staff notified the moment an entry needs review." },
      { icon: FileText, title: "Audit record", desc: "Every verification decision logged and reversible." },
    ],
  },
  "check-in": {
    eyebrow: "Check-in",
    title: <>Check-ins on <span className="text-gradient-cyan">autopilot.</span></>,
    description: "Windowed check-ins with automatic no-show policy. Late arrivals and substitutes resolve by rules — not a sleep-deprived moderator.",
    features: [
      { icon: CheckSquare, title: "Windowed", desc: "Open and close check-in windows precisely on schedule." },
      { icon: Clock, title: "No-show policy", desc: "Automatically forfeit or replace no-shows by your rules." },
      { icon: Users, title: "Substitutes", desc: "Promote subs instantly when a player fails to appear." },
      { icon: Bell, title: "Reminders", desc: "Escalating reminders as the window closes." },
      { icon: Radio, title: "Live status", desc: "Real-time check-in board for staff and players." },
      { icon: Cpu, title: "Auto-seed", desc: "Bracket seeds finalize the moment check-in closes." },
    ],
  },
  teams: {
    eyebrow: "Team Management",
    title: <>Rosters, captains, and <span className="text-gradient-cyan">subs — handled.</span></>,
    description: "Full team lifecycle: invites, roles, roster locks, and substitutions, all synced across brackets and Discord.",
    features: [
      { icon: Users, title: "Roster invites", desc: "Captains build rosters with tracked invites and acceptances." },
      { icon: ShieldCheck, title: "Roster locks", desc: "Lock rosters at deadlines to prevent last-minute stacking." },
      { icon: CheckSquare, title: "Sub management", desc: "Approved substitutes swap in with full audit history." },
      { icon: MessagesSquare, title: "Team channels", desc: "Private team channels provisioned automatically." },
      { icon: BarChart3, title: "Team stats", desc: "Aggregate team performance across every event." },
      { icon: Bell, title: "Roster alerts", desc: "Captains notified of every roster change instantly." },
    ],
  },
  brackets: {
    eyebrow: "Brackets",
    title: <>Brackets that <span className="text-gradient-cyan">heal themselves.</span></>,
    description: "Auto-generated brackets for every format that recompute live and never break — even when players drop.",
    features: [
      { icon: GitBranch, title: "Every format", desc: "Single, double, Swiss, round-robin, and gauntlet." },
      { icon: Trophy, title: "Auto-advance", desc: "Winners advance automatically on score confirmation." },
      { icon: Cpu, title: "Self-healing", desc: "Drops and no-shows resolve without breaking the tree." },
      { icon: Radio, title: "Live updates", desc: "Every spectator sees the same real-time bracket." },
      { icon: Layers, title: "Multi-stage", desc: "Group stages flow into playoffs automatically." },
      { icon: BarChart3, title: "Standings", desc: "Leaderboards and tables recompute instantly." },
    ],
  },
  scheduling: {
    eyebrow: "Scheduling",
    title: <>Schedules that <span className="text-gradient-cyan">manage themselves.</span></>,
    description: "Conflict-aware scheduling across timezones and streams, with reminders and reschedules that ripple automatically.",
    features: [
      { icon: CalendarClock, title: "Auto-schedule", desc: "Generate full match schedules in one click." },
      { icon: Globe2, title: "Timezone-safe", desc: "Everyone sees correct local times, always." },
      { icon: Bell, title: "Reminders", desc: "Timely pings for every match, every participant." },
      { icon: Radio, title: "Live reschedule", desc: "One change updates every dependency instantly." },
      { icon: Server, title: "Stream slots", desc: "Broadcast slot assignment with overlap protection." },
      { icon: Clock, title: "Buffers", desc: "Absorb overruns without cascading delays." },
    ],
  },
  "match-threads": {
    eyebrow: "Match Threads",
    title: <>Every match, its own <span className="text-gradient-cyan">command channel.</span></>,
    description: "Auto-provisioned match threads with score reporting, dispute handling, and a complete audit trail — right inside Discord.",
    features: [
      { icon: MessagesSquare, title: "Auto threads", desc: "A dedicated thread spun up for every single match." },
      { icon: CheckSquare, title: "Score reporting", desc: "Players report scores with confirmation flows." },
      { icon: ShieldCheck, title: "Dispute handling", desc: "Structured dispute resolution with staff escalation." },
      { icon: FileText, title: "Audit trail", desc: "Full history of every message and decision." },
      { icon: Bell, title: "Smart pings", desc: "Only the right people, only when needed." },
      { icon: Radio, title: "Live results", desc: "Confirmed scores flow straight to the bracket." },
    ],
  },
  automation: {
    eyebrow: "Automation",
    title: <>Set the rules. <span className="text-gradient-cyan">Walk away.</span></>,
    description: "Define your policies once and let the engine run the entire operation — registration to results — without intervention.",
    features: [
      { icon: Bot, title: "Policy rules", desc: "Configure once, enforce everywhere, automatically." },
      { icon: Workflow, title: "Event chains", desc: "Actions cascade through dependent systems instantly." },
      { icon: Clock, title: "Scheduled jobs", desc: "Timed actions fire precisely when they should." },
      { icon: Zap, title: "Instant reactions", desc: "Sub-50ms response to every platform event." },
      { icon: Database, title: "Audit log", desc: "Every automated decision recorded immutably." },
      { icon: Radio, title: "Live sync", desc: "All surfaces stay perfectly in step." },
    ],
  },
  dashboard: {
    eyebrow: "Dashboard",
    title: <>One surface for <span className="text-gradient-cyan">the whole operation.</span></>,
    description: "Run hundreds of concurrent events from a single, unified command center — live ops, brackets, players, and analytics.",
    features: [
      { icon: LayoutDashboard, title: "Unified view", desc: "Every event, every status, on one screen." },
      { icon: Radio, title: "Live ops", desc: "Monitor matches in progress in real time." },
      { icon: Users, title: "Player management", desc: "Verify, message, and manage entrants at scale." },
      { icon: BarChart3, title: "Inline analytics", desc: "Key metrics surfaced right where you work." },
      { icon: Bell, title: "Action center", desc: "Everything requiring attention, prioritized." },
      { icon: ShieldCheck, title: "Role-based", desc: "Each staff member sees exactly what they need." },
    ],
  },
  notifications: {
    eyebrow: "Notifications",
    title: <>The right ping, <span className="text-gradient-cyan">at the right time.</span></>,
    description: "Cross-channel notifications — Discord, email, and in-app — that reach the right people exactly when it matters.",
    features: [
      { icon: BellIcon, title: "Multi-channel", desc: "Discord, email, and in-app in one system." },
      { icon: Clock, title: "Perfectly timed", desc: "Reminders fire on schedule, never early or late." },
      { icon: Users, title: "Targeted", desc: "Reach players, captains, or staff precisely." },
      { icon: Globe2, title: "Timezone-aware", desc: "Delivered at sensible local times." },
      { icon: ShieldCheck, title: "Preference-safe", desc: "Respects every recipient's notification settings." },
      { icon: Radio, title: "Event-driven", desc: "Triggered automatically by platform events." },
    ],
  },
  reports: {
    eyebrow: "Reports",
    title: <>Post-event recaps, <span className="text-gradient-cyan">generated instantly.</span></>,
    description: "The moment a final ends, Tournament OS assembles placements, stats, payouts, and a shareable recap — automatically.",
    features: [
      { icon: FileText, title: "Auto recaps", desc: "Complete event summaries the instant it ends." },
      { icon: Trophy, title: "Placements", desc: "Final standings and prize breakdowns computed." },
      { icon: BarChart3, title: "Deep stats", desc: "Per-player and per-team performance reports." },
      { icon: Database, title: "Exports", desc: "CSV and API exports for sponsors and BI." },
      { icon: Users, title: "Sponsor decks", desc: "Branded, shareable results for partners." },
      { icon: Radio, title: "Viewership", desc: "Watch-time and engagement rolled up." },
    ],
  },
};

export const solutionPages: Record<string, MarketingPage> = {
  discord: {
    eyebrow: "Discord Communities",
    title: <>Turn your server into a <span className="text-gradient-cyan">competitive arena.</span></>,
    description: "Everything a community needs to run recurring tournaments — provisioned inside Discord, running on autopilot.",
    stats: [{ value: "1-click", label: "Setup" }, { value: "Free", label: "To start" }, { value: "Auto", label: "Provisioning" }, { value: "24/7", label: "Automation" }],
    features: [
      { icon: MessagesSquare, title: "Native integration", desc: "Roles, channels, and threads created automatically." },
      { icon: Users, title: "Grow engagement", desc: "Recurring events keep your community active." },
      { icon: Trophy, title: "Any game", desc: "Run tournaments for any title your community loves." },
      { icon: Zap, title: "Zero overhead", desc: "Automation handles the logistics for you." },
      { icon: BarChart3, title: "Community stats", desc: "Track participation and top performers." },
      { icon: Bell, title: "Auto reminders", desc: "Keep members informed without lifting a finger." },
    ],
  },
  leagues: {
    eyebrow: "Online Leagues",
    title: <>Run a season-long <span className="text-gradient-cyan">league on rails.</span></>,
    description: "Multi-week leagues with standings, scheduling, and playoffs — all automated, all in one place.",
    stats: [{ value: "Seasons", label: "Multi-week" }, { value: "Auto", label: "Standings" }, { value: "Live", label: "Playoffs" }, { value: "∞", label: "Divisions" }],
    features: [
      { icon: CalendarClock, title: "Season scheduling", desc: "Generate full season calendars automatically." },
      { icon: BarChart3, title: "Live standings", desc: "Tables update as every match resolves." },
      { icon: GitBranch, title: "Playoffs", desc: "Top teams flow into playoffs automatically." },
      { icon: Users, title: "Divisions", desc: "Run unlimited divisions and tiers." },
      { icon: Radio, title: "Promotion/relegation", desc: "Automated movement between tiers." },
      { icon: FileText, title: "Season recaps", desc: "Full-season reports at the finish." },
    ],
  },
  lan: {
    eyebrow: "LAN Events",
    title: <>On-site events, <span className="text-gradient-cyan">flawlessly run.</span></>,
    description: "Check-in stations, station assignment, and live brackets on the big screen — Tournament OS keeps your LAN on schedule.",
    stats: [{ value: "On-site", label: "Check-in" }, { value: "Live", label: "Big screen" }, { value: "Fast", label: "Turnaround" }, { value: "0", label: "Clipboards" }],
    features: [
      { icon: CheckSquare, title: "Station check-in", desc: "Fast on-site check-in at kiosks or by staff." },
      { icon: Server, title: "Station assignment", desc: "Assign matches to physical stations automatically." },
      { icon: GitBranch, title: "Big-screen brackets", desc: "Broadcast-ready bracket displays for the venue." },
      { icon: Clock, title: "Tight scheduling", desc: "Keep a packed LAN day perfectly on time." },
      { icon: MessagesSquare, title: "PA announcements", desc: "Auto-generated call-ups for the next matches." },
      { icon: BarChart3, title: "Live results", desc: "Instant results as matches finish on the floor." },
    ],
  },
  esports: {
    eyebrow: "Esports Organizations",
    title: <>The backbone of your <span className="text-gradient-cyan">competitive program.</span></>,
    description: "Run circuits, qualifiers, and championships at scale with the reliability and data your org and sponsors demand.",
    stats: [{ value: "Scale", label: "Concurrent" }, { value: "SOC 2", label: "Secure" }, { value: "API", label: "Integrations" }, { value: "24/7", label: "Support" }],
    features: [
      { icon: Trophy, title: "Circuit management", desc: "Chain qualifiers into championships seamlessly." },
      { icon: BarChart3, title: "Sponsor data", desc: "Trustworthy, exportable numbers for partners." },
      { icon: ShieldCheck, title: "Verification", desc: "Enterprise-grade eligibility and anti-cheat gating." },
      { icon: Users, title: "Staff console", desc: "Role-based tools for large operations teams." },
      { icon: Network, title: "API & webhooks", desc: "Integrate with your existing stack." },
      { icon: Radio, title: "Broadcast tools", desc: "Overlays and caster views built in." },
    ],
  },
  education: {
    eyebrow: "Colleges & Universities",
    title: <>Collegiate esports, <span className="text-gradient-cyan">professionally run.</span></>,
    description: "Give your program the tools to run intramurals, varsity matches, and inter-collegiate leagues with ease.",
    stats: [{ value: "Roster", label: "Eligibility" }, { value: "Auto", label: "Scheduling" }, { value: "Free", label: "Tier" }, { value: "SSO", label: "Campus" }],
    features: [
      { icon: GraduationCap, title: "Student rosters", desc: "Verify enrollment and eligibility automatically." },
      { icon: CalendarClock, title: "Class-safe scheduling", desc: "Avoid conflicts with academic calendars." },
      { icon: Users, title: "Intramurals", desc: "Run campus-wide leagues effortlessly." },
      { icon: Trophy, title: "Inter-collegiate", desc: "Compete against other schools on one platform." },
      { icon: Lock, title: "Campus SSO", desc: "Sign in with university identity providers." },
      { icon: BarChart3, title: "Program stats", desc: "Report participation to administration." },
    ],
  },
  enterprise: {
    eyebrow: "Enterprise",
    title: <>Global scale, <span className="text-gradient-cyan">enterprise control.</span></>,
    description: "Dedicated infrastructure, SLAs, SSO, data residency, and white-glove migration for the world's largest operators.",
    stats: [{ value: "99.99%", label: "SLA" }, { value: "SSO", label: "SAML/OIDC" }, { value: "Dedicated", label: "Infra" }, { value: "24/7", label: "Support" }],
    features: [
      { icon: Server, title: "Dedicated infra", desc: "Isolated, dedicated infrastructure with SLAs." },
      { icon: Lock, title: "SSO & SAML", desc: "Enterprise identity and access management." },
      { icon: Database, title: "Data residency", desc: "Control where your data is stored." },
      { icon: ShieldCheck, title: "SOC 2 · ISO", desc: "Independently audited security controls." },
      { icon: Network, title: "Custom integrations", desc: "Deep integration with your systems." },
      { icon: Users, title: "White-glove", desc: "Dedicated migration and success teams." },
    ],
  },
};
